# version: '3.8'
#MongoDB 5.0+ requires a CPU with AVX support, => sử dụng image: mongo:4.4
services:
  be-nest:
    build:
      context: .
      dockerfile: Dockerfile
    # restart: unless-stopped
    expose:
      - 8080
    ports:
      - 8080:8080
    env_file:
      - .env


    # docker compose -p hoidanit-nest up -d